package lesson06;

enum EuropeCoutnries {
    RUSSIA, GERMANY, UNITEDKINGDOM, FRANCE, ITALY, SPAIN, UKRAINE,
    POLAND, ROMANIA, NETHERLANDS, BELGIUM, CZECHREPUBLIC, GREECE, PORTUGAL,
    SWEDEN, HUNGARY, BELARUS, AUSTRIA, SERBIA, SWITZERLAND, BULGARIA, DENMARK, FINLAND,
    SLOVAKIA, NORWAY, IRELAND, CROATIA, MOLDOVA, BOSNIAANDHERZEGOVINA, ALBANIA, LITHUANIA,
    NORTHMAVCEDONIA, SLOVENIA, LATVIA, ESTONIA, MONTENEGRO, LUXEMBOURG, MALTA, ICELAND,
    ANDORRA, MONACO, LIECHTENSTEIN, SANMARINA, HOLYSEE

}
